CONTIKI_CPU_DIRS += . init/common

CONTIKI_SOURCEFILES += gdt.c helpers.S idt.c cpu.c

CC       = gcc
LD       = ld
AS       = as
OBJCOPY  = objcopy
SIZE     = size
STRIP    = strip

CFLAGS  += -Wall -g
LDFLAGS += -Map=contiki-$(TARGET).map --build-id=none
