CONTIKI_CPU_DIRS = . dev

CONTIKI_SOURCEFILES += stack.c
CONTIKI_SOURCEFILES += uart0.c uart1.c uart-intr.c
CONTIKI_SOURCEFILES += dma.c dma_intr.c
CONTIKI_SOURCEFILES += cc2530-rf.c
CONTIKI_SOURCEFILES += watchdog.c
CONTIKI_SOURCEFILES += port2-intr.c port2.c

include $(CONTIKI_CPU)/usb/Makefile.usb

include $(CONTIKI_CPU)/../common/Makefile.common
